### ISSUE TITLE
CMS Controller 1.3.1 - phase command

### ISSUE THREAD

**Issue by spkenyon** [myclark/CMSPulserReleases#4]
The newest controller client still has the same phase sign issue... -90 degrees is actually 90 degrees, and vice versa, based on our convention (zero degrees is the zero crossing on the rising edge of the sinusoid, see attachment for the degrees convention)
![image](https://user-images.githubusercontent.com/71351736/109181602-1bacbf00-775a-11eb-9dca-2045b95d1f56.png)

**Comment by myclark** [comment]
Added a FPGA fabric subsystem and corresponding client control to allow 180 degrees phase flipping of the reference clock in release V1.3.2.
